FROM python:3.11.5-slim
WORKDIR /home
COPY ./requirements.txt ./
COPY ./src ./src/
COPY ./assets ./assets/
RUN \
apt-get update && \
apt-get upgrade -y && \
apt-get autoremove -y && \
apt-get clean -y && \
pip install --upgrade pip && \
pip install wheel && \
pip install -r requirements.txt
EXPOSE 8501
CMD ["streamlit", "run", "src/streamlit.py"]